### ISSUE TITLE
No such interface supported at EnvDTE.StatusBar.set_Text(String pTextc)

### ISSUE THREAD

**Issue by icnocop** [vercellone/tfsautoshelve#17]
Windows 7 Enterprise 64-bit
Visual Studio 2013
TFS Auto Shelve v4.2
I occasionally experience Visual Studio 2013 crashing when exiting and found this exception in "C:\Users\username\Documents\Visual Studio 2013\crash_3_28_2016 4_40_08 PM.log":

```
Exception Type       : System.InvalidCastException
Exception Message    : No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))
Exception Stack Trace:    at EnvDTE.StatusBar.set_Text(String pTextc)
   at VsExt.AutoShelve.VsExtAutoShelvePackage.WriteToStatusBar(String text)
   at VsExt.AutoShelve.VsExtAutoShelvePackage.WriteException(Exception ex)
   at VsExt.AutoShelve.VsExtAutoShelvePackage.autoShelve_OnShelvesetCreated(Object sender, ShelvesetCreatedEventArgs e)
   at VsExt.AutoShelve.TfsAutoShelve.CreateShelveset(Boolean force)
   at VsExt.AutoShelve.TfsAutoShelve.<GetAutoShelveCallback>b__b(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
Exception Data   : [EmptyOrNull]
```

**Comment by vercellone** [comment]
I suppose I could make WriteToStatusBar, WriteLineToOutputWindow, and WriteToActivityLog swallow exceptions.

**Comment by icnocop** [comment]
Thank you.
I'm thinking that this add-in should catch all exceptions and just log them.
This add-in should not throw exceptions to the Visual Studio IDE host process.

**Comment by vercellone** [comment]
Please get the [latest VSIX from appveyor](https://ci.appveyor.com/api/projects/vercellone/tfsautoshelve/artifacts/VsExt.AutoShelve/bin/Release/VsExt.AutoShelve.vsix) and report back.  If all is well I'll publish this to the visual studio gallery.

**Comment by vercellone** [comment]
My mistake.  You did specify Visual Studio 2013 and TFS Auto Shelve v4.2.  I'm reopening this issue until I can backport/merge recent v5 fixes into v4.

**Comment by vercellone** [comment]
Fixed #17 in commit 76a741b. 

Please install [TfsAutoShelve2013v4.3.vsix](https://ci.appveyor.com/api/buildjobs/h2h98qq0q97yl7v6/artifacts/VsExt.AutoShelve/bin/Package/TfsAutoShelve2013v4.3.vsix) and report back. If all is well I'll publish it to the visual studio gallery.

**Comment by icnocop** [comment]
Thank you. Visual Studio 2013 is no longer crashing on exit. :+1:

**Comment by vercellone** [comment]
Thank you for all your feedback.  I just published the latest to the Visual Studio Gallery:
- [TFS Auto Shelve for Visual Studio 2013 v4.3](https://visualstudiogallery.msdn.microsoft.com/ae71e276-e35e-47d3-915d-61a5a38de33b)
- [TFS Auto Shelve for Visual Studio 2015 v5.4](https://visualstudiogallery.msdn.microsoft.com/8a8c753d-e10e-42b2-940e-2f6e8ed68d84)
